use exemplos;


create table MONTADORA (
	ID INT not null auto_increment,
	NOME VARCHAR(255) NOT NULL,
	PAIS VARCHAR(255) NOT NULL,
	NOME_PRESIDENTE VARCHAR(255) NOT NULL,
    DATA_FUNDACAO DATE not null,
	CONSTRAINT ID_MONTADORA_PK PRIMARY KEY (ID)
);

create table CARRO (
	ID INT not null auto_increment,
	ID_MONTADORA INT NOT NULL,
	MODELO VARCHAR(255) NOT NULL,
	PLACA VARCHAR(255) NOT NULL,
	ANO INT not null,
	VALOR DECIMAL(10 , 2),
	CONSTRAINT ID_CARRO_PK PRIMARY KEY (ID),
    CONSTRAINT ID_MONTADORA_FK FOREIGN KEY (ID_MONTADORA) REFERENCES MONTADORA (ID)
);


INSERT INTO MONTADORA (NOME, PAIS, NOME_PRESIDENTE, DATA_FUNDACAO) VALUES ('Toyota', 'Japão', 'Akio Toyoda', '1937-08-28');
INSERT INTO MONTADORA (NOME, PAIS, NOME_PRESIDENTE, DATA_FUNDACAO) VALUES ('Ford', 'Estados Unidos', 'Jim Farley', '1903-06-16');
INSERT INTO MONTADORA (NOME, PAIS, NOME_PRESIDENTE, DATA_FUNDACAO) VALUES ('Volkswagen', 'Alemanha', 'Herbert Diess', '1937-05-28');
INSERT INTO MONTADORA (NOME, PAIS, NOME_PRESIDENTE, DATA_FUNDACAO) VALUES ('GM', 'Estados Unidos', 'Mary Barra', '1908-09-16');
INSERT INTO MONTADORA (NOME, PAIS, NOME_PRESIDENTE, DATA_FUNDACAO) VALUES ('Honda', 'Japão', 'Toshihiro Mibe', '1948-09-24');


INSERT INTO CARRO (ID_MONTADORA, MODELO, PLACA, ANO, VALOR) VALUES (1, 'Corolla', 'ABC-1234', 2020, 30000.00);
INSERT INTO CARRO (ID_MONTADORA, MODELO, PLACA, ANO, VALOR) VALUES (2, 'Mustang', 'DEF-5678', 2019, 55000.00);
INSERT INTO CARRO (ID_MONTADORA, MODELO, PLACA, ANO, VALOR) VALUES (3, 'Golf', 'GHI-9101', 2021, 28000.00);
INSERT INTO CARRO (ID_MONTADORA, MODELO, PLACA, ANO, VALOR) VALUES (4, 'Camaro', 'JKL-1213', 2020, 45000.00);
INSERT INTO CARRO (ID_MONTADORA, MODELO, PLACA, ANO, VALOR) VALUES (5, 'Civic', 'MNO-1415', 2021, 32000.00);

select * from montadora m;
select * from carro c;



